### PR TITLE
Additional function support and case sensitivity fixes

### PR DESCRIPTION
**Pull request by markgould**
This adds support for additional functions and fixes issues with case sensitivity (for example maybe someone has edited RDL by hand)
  - IsNothing
  - String.Empty
  - CountDistinct (this has to be implemented a little weirdly, I can make any changes if you have feedback)
  - FormatDateTime
  - DateFormat.ShortDate

### CODE REVIEW

**Comment by k0st1x** [comment]
"ShortDate" - is platform/region specific  format. please update the "{0:MM/dd/yyyy}" to "{0:d}".


```cs
string.Equals(property, "Value", StringComparison.CurrentCultureIgnoreCase)
```
please use the StringComparison.InvariantCultureIgnoreCase here

**Comment by markgould** [comment]
Corrected, thanks!

**Comment by k0st1x** [comment]
@markgould can we use your merged code in the DevExpress .NET Reporting (which is closed-source product) in the [VisualStudio Report Designer import reports](https://docs.devexpress.com/XtraReports/1468/get-started-with-devexpress-reporting/convert-third-party-reports-to-devexpress-reports#visual-studio-report-designer) functionality?

**Comment by markgould** [comment]
Yes, feel free to use it in there. I have no issues with that.

**Pull request merged**
